version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: remindr-postgres
    environment:
      POSTGRES_USER: remindr
      POSTGRES_PASSWORD: remindr123
      POSTGRES_DB: remindr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 