#!/bin/bash

echo "🐘 Neon PostgreSQL Setup Helper"
echo "==============================="
echo ""

echo "🔗 Quick Links:"
echo "   → Neon Console: https://console.neon.tech"
echo "   → GitHub Environments: https://github.com/shaibs3/DateKeeper/settings/environments"
echo ""

echo "📋 Neon Database Strategy Options:"
echo ""

echo "Option 1: Single Project with Branches (Recommended)"
echo "   ✅ Cost-effective (one project)"
echo "   ✅ Easy to manage"
echo "   ✅ Database branching like Git"
echo ""
echo "   Setup:"
echo "   1. Create one Neon project: 'DateKeeper'"
echo "   2. Use 'main' branch for production"
echo "   3. Create 'staging' branch for staging"
echo "   4. Each branch has its own connection string"
echo ""

echo "Option 2: Separate Projects"
echo "   ✅ Complete isolation"
echo "   ✅ Different regions possible"
echo "   ❌ Higher cost (two projects)"
echo ""
echo "   Setup:"
echo "   1. Create project: 'DateKeeper-Production'"
echo "   2. Create project: 'DateKeeper-Staging'"
echo "   3. Each project has its own connection string"
echo ""

echo "🛠️ Connection String Examples:"
echo ""
echo "Standard connection (direct):"
echo "postgresql://username:password@ep-abc123.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo ""
echo "Pooled connection (recommended for production):"
echo "postgresql://username:password@ep-abc123-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo ""

echo "⚡ Neon-Specific Tips:"
echo "   → Use pooled connections for production (better performance)"
echo "   → Databases auto-suspend after inactivity (saves money)"
echo "   → First query after suspend may take 1-2 seconds (cold start)"
echo "   → SSL is required (?sslmode=require)"
echo "   → Connection pooling is built-in with -pooler endpoints"
echo ""

echo "🧪 Test Your Connection:"
echo "   1. Copy your Neon connection string"
echo "   2. Add to .env.local: DATABASE_URL='your-connection-string'"
echo "   3. Run: npx prisma db pull"
echo "   4. If successful, you'll see 'Introspected X models'"
echo ""

echo "🚀 Ready to configure Neon for production!"
echo ""
echo "Next steps:"
echo "1. Go to https://console.neon.tech"
echo "2. Set up your databases (single project with branches recommended)"
echo "3. Copy connection strings"
echo "4. Add to GitHub Environment Secrets"
echo "5. Deploy and enjoy serverless PostgreSQL! 🎉"
