#!/bin/bash

echo "🚀 Vercel Environment Variables Setup Guide"
echo "==========================================="
echo ""

echo "📍 Where to Set Variables:"
echo "   → Go to: https://vercel.com/dashboard"
echo "   → Select your DateKeeper project"
echo "   → Settings → Environment Variables"
echo ""

echo "🎯 Required Environment Variables:"
echo ""

echo "📊 PRODUCTION Environment:"
echo "   Variable Name: DATABASE_URL"
echo "   Value: [Your Neon production connection string]"
echo "   Environment: Production"
echo ""
echo "   Variable Name: NEXTAUTH_SECRET"
echo "   Value: [Generate with: openssl rand -base64 32]"
echo "   Environment: Production"
echo ""
echo "   Variable Name: NEXTAUTH_URL"
echo "   Value: https://datekeeper.vercel.app"
echo "   Environment: Production"
echo ""
echo "   Variable Name: GOOGLE_CLIENT_ID"
echo "   Value: [Your production Google OAuth client ID]"
echo "   Environment: Production"
echo ""
echo "   Variable Name: GOOGLE_CLIENT_SECRET"
echo "   Value: [Your production Google OAuth client secret]"
echo "   Environment: Production"
echo ""
echo "   Variable Name: APP_ENV"
echo "   Value: production"
echo "   Environment: Production"
echo ""

echo "🧪 PREVIEW Environment (Staging):"
echo "   Variable Name: DATABASE_URL"
echo "   Value: [Your Neon staging connection string]"
echo "   Environment: Preview"
echo ""
echo "   Variable Name: NEXTAUTH_SECRET"
echo "   Value: [Different secret for staging]"
echo "   Environment: Preview"
echo ""
echo "   Variable Name: NEXTAUTH_URL"
echo "   Value: https://datekeeper-staging.vercel.app"
echo "   Environment: Preview"
echo ""
echo "   Variable Name: GOOGLE_CLIENT_ID"
echo "   Value: [Your staging Google OAuth client ID]"
echo "   Environment: Preview"
echo ""
echo "   Variable Name: GOOGLE_CLIENT_SECRET"
echo "   Value: [Your staging Google OAuth client secret]"
echo "   Environment: Preview"
echo ""
echo "   Variable Name: APP_ENV"
echo "   Value: staging"
echo "   Environment: Preview"
echo ""

echo "🔐 Security Best Practices:"
echo "   → Use different secrets for production and staging"
echo "   → Use separate Google OAuth apps for each environment"
echo "   → Use separate Neon databases/branches for each environment"
echo "   → Never commit secrets to Git"
echo ""

echo "🛠️ How to Generate NEXTAUTH_SECRET:"
echo "   Method 1: openssl rand -base64 32"
echo "   Method 2: https://generate-secret.vercel.app/32"
echo "   Method 3: node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\""
echo ""

echo "📋 Vercel Environment Types:"
echo "   → Production: Used for your main domain (datekeeper.vercel.app)"
echo "   → Preview: Used for staging and PR deployments"
echo "   → Development: Used for local development (not needed for this setup)"
echo ""

echo "✅ Verification Steps:"
echo "   1. Add all variables in Vercel Dashboard"
echo "   2. Deploy your app (push to main branch)"
echo "   3. Check deployment logs for successful database connection"
echo "   4. Test authentication on your deployed app"
echo "   5. Verify database operations work"
echo ""

echo "🔧 Troubleshooting:"
echo "   → If variables don't appear: Wait 1-2 minutes and redeploy"
echo "   → If database connection fails: Check DATABASE_URL format"
echo "   → If auth fails: Verify NEXTAUTH_SECRET and Google OAuth settings"
echo "   → If wrong environment: Check environment selection in Vercel"
echo ""

echo "🎉 Once complete, your app will have:"
echo "   → Database connectivity in production and staging"
echo "   → Working authentication with Google OAuth"
echo "   → Proper environment separation"
echo "   → Secure secret management"
echo ""

echo "🚀 Ready to set up your Vercel environment variables!"
