name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Create .env file with dummy values
        run: |
          echo "GOOGLE_CLIENT_ID=dummy" >> .env
          echo "GOOGLE_CLIENT_SECRET=dummy" >> .env
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env
          echo "NEXTAUTH_SECRET=dummy" >> .env
          echo "DATABASE_URL=postgresql://user:pass@localhost:5432/db" >> .env

      - name: Run type checking
        run: npm run type-check

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build application
        run: |
          npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Run test coverage
        run: npm run test:coverage

  security:
    name: Security
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit
      
      - name: Run npm audit fix
        run: npm audit fix --dry-run 